### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by biemster** [j0r1/qtwebenginewebrtc#1]
For someone who never did Qt dev work (like me), it's not clear how to build this code. I guess Qt Creator is involved?
I'll go figure that out now, but a couple pointers here and there in the Readme would be much appreciated!

**Comment by JLiesenborgs** [comment]
Just running 'qmake' to generate a Makefile, and then 'make' to build the program is what works for me.

**Comment by biemster** [comment]
That worked for me too!
